---
- name: Prepare OpenShift Hosts
  hosts:
    - masters
    - nodes
  remote_user: ec2-user
  become: true

  vars_prompt:
  - name: "RHN_USERNAME"
    prompt: "Enter Red Hat username"
    default: "{{ lookup('env','RHN_USERNAME') }}"
    private: no
  - name: "RHN_PASSWORD"
    prompt: "Enter  Red Hat password"
    default: "{{ lookup('env','RHN_PASSWORD') }}"
    private: yes
  - name: "RHN_POOL"
    prompt: "Enter  Red Hat Subscription Pool ID"
    default: "8a85f98c60c2c2b40160c324e5d21d70"
    private: yes

  tasks:
  - name: Set hostnames
    hostname:
      name: '{{ inventory_hostname }}'

  - name: Register systems and attach them to the pool
    redhat_subscription:
      state: present
      force_register: yes
      username: '{{ RHN_USERNAME }}'
      password: '{{ RHN_PASSWORD }}'
      pool: '{{ RHN_POOL }}'

  - name: Disable all the repositories
    command: 'subscription-manager repos --disable="*"'
    ignore_errors: True

  - name: Enable OpenShift repositories
    command: 'subscription-manager repos \
              --enable=rhel-7-server-rpms \
              --enable=rhel-7-server-extras-rpms \
              --enable=rhel-7-server-ose-3.11-rpms \
              --enable=rhel-7-server-ansible-2.6-rpms'

  - name: Install packages
    yum:
      name:
        - wget
        - git
        - net-tools
        - bind-utils
        - yum-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - docker
      state: latest
